[build]
target = "thumbv7em-none-eabihf"

[run]
target = "thumbv7em-none-eabihf"   

[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip STM32F411CEUx'

rustflags = [
  "-C", "link-arg=-Tlink.x",
]
 